#!/bin/bash

cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf

maincf=$(
   cat <<POSTFIX_CONF
inet_protocols = ipv4
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 ${POSTFIX_MYNETWORKS}

POSTFIX_CONF
   )

echo "$maincf" >> /etc/postfix/main.cf

if [ -n "${POSTFIX_RELAYHOST}" ]; then
   relayhost=$(
   cat <<POSTFIX_CONF_RELAYHOST
relayhost = ${POSTFIX_RELAYHOST}

POSTFIX_CONF_RELAYHOST
   )

   echo "$relayhost" >> /etc/postfix/main.cf

   if [ -n "${POSTFIX_RELAYHOST_SASLAUTH}" ]; then
      sasl=$(
      cat <<POSTFIX_CONF_RELAYHOST_SASL
smtp_use_tls = yes
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = texthash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
smtp_tls_security_level = encrypt

POSTFIX_CONF_RELAYHOST_SASL
      )

      echo "$sasl" >> /etc/postfix/main.cf

      texthash=$(
      cat <<SASLAUTH
${POSTFIX_RELAYHOST}    ${POSTFIX_RELAYHOST_SASLAUTH}

SASLAUTH
      )

           echo "$texthash" >> /etc/postfix/sasl_passwd
   fi

fi
